### PR TITLE
latest changes

### PR DESCRIPTION
**Pull request by the0ne**
added synced "checked" flag (strike-through)
added support for qr-code scanning and ean->product resolution
etc.

please test it out thoroughly.

### CODE REVIEW

**Comment by ghost** [comment]
We must update the APP in the fdroid store.

Am 21. August 2018 16:55:54 MESZ schrieb "Thomas E. Horner" <notifications@github.com>:
>added web ui at /index.php (note: android app endpoint needs to end
>with .../api.php)
>added synced "checked" flag (strike-through)
>added local config file support to avoid overwriting local settings on
>update
>added support for qr-code scanning and ean->product resolution
>etc.
>
>please test it out thoroughly.
>You can view, comment on, or merge this pull request online at:
>
>  https://github.com/GroundApps/ShoppingList/pull/65
>
>-- Commit Summary --
>
>  * Fixed dependency download by upgrading gradle
>  * Fixed dependeny
>  * Fixed missing context in logger
>  * Added save and update of checked attribute
>* Added option to scan QR code using the front camera (for a wall
>mounted tablet)
>  * Workaround for repeating items when scrolling list
>  * Fixed parsing the backend response when deleting items
>  * Menu access to cached list, save checkmarks in cached list
>  * Option to hide checked items
>  * Change front camera selection and use a checkbox
>  * Raised compile SDK and build tools version
>* Added option to add item by scanning a qr code (needs backend
>support)
>  * Added option to rename and delete a selected item
>  * Fix missing icon for add item by qr code
>  * Fix missing close of main menu when starting qr code scan
>  * Fix using the front camera when set in preferences
>  * Fix keeping list position after update
>  * Fix crash when api is already busy: Skip updating list
>  * updated to latest gradle
>  * updated by android studio
>
>-- File Changes --
>
>    D .idea/.name (1)
>    A .idea/caches/build_file_checksums.ser (0)
>    A .idea/codeStyles/Project.xml (29)
>    D .idea/compiler.xml (22)
>    D .idea/copyright/profiles_settings.xml (3)
>    D .idea/encodings.xml (6)
>    M .idea/gradle.xml (2)
>    M .idea/misc.xml (22)
>    M .idea/vcs.xml (2)
>    M ShoppingList.iml (2)
>    M app/app.iml (108)
>    M app/build.gradle (18)
>    M app/src/main/java/org/janb/shoppinglist/CONSTS.java (1)
>    M app/src/main/java/org/janb/shoppinglist/LOGGER.java (3)
>M app/src/main/java/org/janb/shoppinglist/activity/MainActivity.java
>(17)
>    M app/src/main/java/org/janb/shoppinglist/api/ListAPI.java (15)
>M
>app/src/main/java/org/janb/shoppinglist/fragments/CacheListFragment.java
>(18)
>M
>app/src/main/java/org/janb/shoppinglist/fragments/SettingsFragment.java
>(2)
>M
>app/src/main/java/org/janb/shoppinglist/fragments/ShoppingListFragment.java
>(110)
>M
>app/src/main/java/org/janb/shoppinglist/model/ShoppingListAdapter.java
>(27)
>M app/src/main/java/org/janb/shoppinglist/model/ShoppingListItem.java
>(10)
>    A app/src/main/res/drawable/ic_delete_white_24dp.png (0)
>    A app/src/main/res/drawable/ic_photo_camera_black_48dp.png (0)
>    M app/src/main/res/layout/dialog_add_custom.xml (1)
>    M app/src/main/res/layout/dialog_update_item.xml (27)
>    M app/src/main/res/layout/fragment_list.xml (9)
>    A app/src/main/res/layout/list_row_hidden.xml (5)
>    M app/src/main/res/menu/menu_main.xml (4)
>    M app/src/main/res/values-de/strings.xml (6)
>    M app/src/main/res/values/strings.xml (6)
>    M app/src/main/res/xml/preferences.xml (4)
>    M build.gradle (5)
>    M gradle/wrapper/gradle-wrapper.properties (4)
>
>-- Patch Links --
>
>https://github.com/GroundApps/ShoppingList/pull/65.patch
>https://github.com/GroundApps/ShoppingList/pull/65.diff
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/GroundApps/ShoppingList/pull/65

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by the0ne** [comment]
yes we should. definitely.

**Comment by ghost** [comment]
Could you Marke a apk so i could test it.

Am 21. August 2018 17:00:24 MESZ schrieb "Thomas E. Horner" <notifications@github.com>:
>yes we should. definitely.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/GroundApps/ShoppingList/pull/65#issuecomment-414705698

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by ghost** [comment]
The last update in the store is two years old and has a security issue.

Am 21. August 2018 17:00:24 MESZ schrieb "Thomas E. Horner" <notifications@github.com>:
>yes we should. definitely.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/GroundApps/ShoppingList/pull/65#issuecomment-414705698

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by the0ne** [comment]
@beli3ver here's the program version I use since August. Sorry for missing to provide it earlier: [shoppinglist-debug.zip](https://github.com/GroundApps/ShoppingList/files/3007547/shoppinglist-debug.zip)

**Pull request merged**
